---
title: "Data"
output:
  html_document: 
    toc: true
    toc_float: true
---

Two datasets will be used in the short course, both available as part of the `VectraPolarisData` package on Bioconductor. I also provide processed versions of these datasets as  `.rdata` objects, and an exampled `.tiff` image from the lung cancer dataset.

They are below with brief descriptions.

## Ovarian cancer data

This is a segmented and phenotyped multiplex immunoflurescence dataset of tumor microarray images of high grade serous ovarian cancer, used in [this study](https://aacrjournals.org/mcr/article/19/12/1973/675069/The-Spatial-Context-of-Tumor-Infiltrating-Immune). The full data are part of the `VectraPolarisData` package. 


A cleaned version of the data can be found [here](./Data/ovarian.RDA).


## Lung cancer

This is a segmented and phenotyped multiplex immunoflurescence dataset of non small cell lung carcinoma tissue, used in [this study](https://pubmed.ncbi.nlm.nih.gov/34048945/). The full data are part of the `VectraPolarisData` package, and contain multiple regions of interest (ROIs) for each subject. 


A cleaned version of the data can be found [here](./Data/lung.RDA).

An example multichannel tiff image can be found [here](./Data/lung_component_data.tif), with binary segmentation maps [here](./Data/lung_binary_seg_maps.tif), and a composite image [here](./Data/lung.tif).


